"""add relation at user chat message

Revision ID: 0de285fdd263
Revises: 71017515fbf7
Create Date: 2025-10-13 20:42:23.561328

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0de285fdd263'
down_revision: Union[str, Sequence[str], None] = '71017515fbf7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('yott_message',
    sa.Column('mid', sa.Integer(), nullable=False),
    sa.Column('s_id', sa.String(length=60), nullable=True),
    sa.Column('data', sa.String(length=500), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('mid'),
    sa.UniqueConstraint('s_id')
    )
    op.create_table('message_belong_to',
    sa.Column('message_id', sa.Integer(), nullable=True),
    sa.Column('chat_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['chat_id'], ['yott_chat.cid'], ),
    sa.ForeignKeyConstraint(['message_id'], ['yott_message.mid'], )
    )
    op.create_table('user_belong_to',
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('chat_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['chat_id'], ['yott_chat.cid'], ),
    sa.ForeignKeyConstraint(['user_id'], ['yott_person.uid'], )
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_belong_to')
    op.drop_table('message_belong_to')
    op.drop_table('yott_message')
    # ### end Alembic commands ###
