"""chage id type to int

Revision ID: 0e295b6fc265
Revises: 
Create Date: 2025-10-15 21:00:38.749571

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0e295b6fc265'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('yott_chat',
    sa.Column('cid', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=True),
    sa.Column('is_groupchat', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('cid')
    )
    op.create_table('yott_person',
    sa.Column('uid', sa.Integer(), nullable=False),
    sa.Column('email', sa.Text(), nullable=True),
    sa.Column('given_name', sa.Text(), nullable=True),
    sa.Column('family_name', sa.Text(), nullable=True),
    sa.Column('preferred_username', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_table('yott_message',
    sa.Column('mid', sa.Integer(), nullable=False),
    sa.Column('data', sa.Text(), nullable=True),
    sa.Column('s_id', sa.Integer(), nullable=True),
    sa.Column('cid', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['cid'], ['yott_chat.cid'], ),
    sa.ForeignKeyConstraint(['s_id'], ['yott_person.uid'], ),
    sa.PrimaryKeyConstraint('mid')
    )
    op.create_table('yott_user_belong_to_chat',
    sa.Column('rid', sa.Integer(), nullable=False),
    sa.Column('uid', sa.Integer(), nullable=True),
    sa.Column('cid', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cid'], ['yott_chat.cid'], ),
    sa.ForeignKeyConstraint(['uid'], ['yott_person.uid'], ),
    sa.PrimaryKeyConstraint('rid')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('yott_user_belong_to_chat')
    op.drop_table('yott_message')
    op.drop_table('yott_person')
    op.drop_table('yott_chat')
    # ### end Alembic commands ###
