"""fix minor problems

Revision ID: 71017515fbf7
Revises: f6d431c86de2
Create Date: 2025-10-12 16:20:57.853031

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '71017515fbf7'
down_revision: Union[str, Sequence[str], None] = 'f6d431c86de2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('yott_person_email_key'), 'yott_person', type_='unique')
    op.drop_constraint(op.f('yott_person_family_name_key'), 'yott_person', type_='unique')
    op.drop_constraint(op.f('yott_person_given_name_key'), 'yott_person', type_='unique')
    op.drop_constraint(op.f('yott_person_preferred_username_key'), 'yott_person', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('yott_person_preferred_username_key'), 'yott_person', ['preferred_username'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('yott_person_given_name_key'), 'yott_person', ['given_name'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('yott_person_family_name_key'), 'yott_person', ['family_name'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('yott_person_email_key'), 'yott_person', ['email'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
