"""patch db2

Revision ID: f6d431c86de2
Revises: 0e65c1e1e60d
Create Date: 2025-10-12 01:04:05.325288

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f6d431c86de2'
down_revision: Union[str, Sequence[str], None] = '0e65c1e1e60d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('yott_chat',
    sa.Column('cid', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=True),
    sa.Column('is_groupchat', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('cid'),
    sa.UniqueConstraint('name')
    )
    op.create_table('yott_person',
    sa.Column('uid', sa.UUID(), nullable=False),
    sa.Column('email', sa.Text(), nullable=True),
    sa.Column('given_name', sa.Text(), nullable=True),
    sa.Column('family_name', sa.Text(), nullable=True),
    sa.Column('preferred_username', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('uid'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('family_name'),
    sa.UniqueConstraint('given_name'),
    sa.UniqueConstraint('preferred_username')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('yott_person')
    op.drop_table('yott_chat')
    # ### end Alembic commands ###
